name: code_compiles

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: actions/checkout@v3

      - name: Install prerequired packages
        # To compile and run the code we require cmake, ninja and opencv
        run: sudo apt-get update && sudo apt-get install build-essential cmake ninja-build libopencv-dev

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          sudo rosdep init || true
          rosdep update
          rosdep install --from-paths src -y --ignore-src

      - name: Colcon build
        working-directory: ${{ github.workspace }}
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-select face_detector
